function.name: getTextMessage
spring:
  cloud:
    function:
      definition: getTextMessage
weather:
  # In case we get 501 - authorization errors, we need to renew Apikey from AccuWeather api
  apikey: vepGhGOGs61aphrJTBYmSEBAqePL9OnA
  base: http://dataservice.accuweather.com/
  search: locations/v1/search?q=
  daily: forecasts/v1/daily/1day/
  query: stockholm
  country: sweden


