function.name: getTextMessage
spring:
  cloud:
    function:
      definition: getTextMessage
weather:
  #  We need to renew ApiKey after several api call.
  apikey: FZ3Orkuld6gzXQXrmpdoafqbEXwPVXY9
  base: http://dataservice.accuweather.com/
  search: locations/v1/search?q=
  daily: forecasts/v1/daily/1day/
  query: stockholm
  country: sweden


